#!/bin/bash
#
#  xcoind The X Coin server.
#
#
# chkconfig: 345 80 20
# description: xcoind
# processname: xcoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/xcoind, see below
if [ -f /etc/sysconfig/xcoind ]; then
        . /etc/sysconfig/xcoind
fi

RETVAL=0

prog=xcoind
# you can override the lockfile via XCOIND_LOCKFILE in /etc/sysconfig/xcoind
lockfile=${XCOIND_LOCKFILE-/var/lock/subsys/xcoind}

# xcoind defaults to /usr/bin/xcoind, override with XCOIND_BIN
xcoind=${XCOIND_BIN-/usr/bin/xcoind}

# xcoind opts default to -disablewallet, override with XCOIND_OPTS
xcoind_opts=${XCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $xcoind $xcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
